### ISSUE TITLE
*.addin file

### ISSUE THREAD

**Issue by ErwinMeulman** [DavidVeld/CarboLifeCalc#1]
Hoi David,

met welke addin-file kan ik het programma starten?

mvg erwin

**Comment by DavidVeld** [comment]
Hoi Erwin, deze zul je atm zelf moeten aanmaken; 

//Afhankelijk waar je de build directory hebt;

maak een addin file and edit als :

<?xml version="1.0" encoding="utf-8"?>
<RevitAddIns>
  <AddIn Type="Application">
    <Name>CarboLifeRevit</Name>
    <Assembly>C:\CarboLifeCalc\CarboLifeRevit.dll</Assembly>
    <AddInId>211bd833-33a4-432b-9792-c5ecffa4e744</AddInId>
    <FullClassName>CarboLifeRevit.CarboLifeMenu</FullClassName>
    <VendorId>DavidVeld</VendorId>
    <VendorDescription>DavidVeld, www.davidveld.nl</VendorDescription>
  </AddIn>
</RevitAddIns>

Copy: C:\ProgramData\Autodesk\Revit\Addins

Regards,
